name: "Decision-Making Under Risk Preferences"
description: >
  A simple demo survey exploring preferences when making decisions under risk.
  Attributes cover potential upside, rewardvariability, worst-case outcome, and timing.

attributes:
  - name: Gain Amount
    levels:
      - "€20"
      - "€60"
      - "€120"
      - "€240"

  - name: Loss Amount (Worst-Case Outcome)
    levels:
      - "€0"
      - "−€20"
      - "−€60"
      - "−€120"

  - name: Probability of Gain
    levels:
      - "20%"
      - "40%"
      - "60%"
      - "80%"

  - name: Delay of Outcome
    levels:
      - Immediate
      - In 1 week
      - 1 month
      - 3 months

# These can be changed to fit the needs of the survey
settings:
  screening_pages: 5
  scenarios_per_page: 4
  max_unacceptable_questions: 4
  max_must_have_questions: 3
  choice_tournament_size: 3
  unacceptable_threshold: 0.75
  must_have_threshold: 0.90
